version: '3'
services:
  db:
    image: postgres:15.1
    container_name: todo_api_db
    restart: always
    environment:
      POSTGRES_USER: grudzug
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: todo_api_db
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
